find_package(PkgConfig QUIET)
find_package(Threads REQUIRED)

add_library(wordle_json INTERFACE)
find_package(nlohmann_json CONFIG QUIET)
if(TARGET nlohmann_json::nlohmann_json)
    target_link_libraries(wordle_json INTERFACE nlohmann_json::nlohmann_json)
else()
    if(PkgConfig_FOUND)
        pkg_check_modules(JSON QUIET IMPORTED_TARGET nlohmann_json)
    endif()
    if(TARGET PkgConfig::JSON)
        target_link_libraries(wordle_json INTERFACE PkgConfig::JSON)
    else()
        find_path(NLOHMANN_JSON_INCLUDE_DIR nlohmann/json.hpp)
        if(NOT NLOHMANN_JSON_INCLUDE_DIR)
            message(FATAL_ERROR "Install nlohmann-json or set NLOHMANN_JSON_INCLUDE_DIR")
        endif()
        target_include_directories(wordle_json INTERFACE ${NLOHMANN_JSON_INCLUDE_DIR})
    endif()
endif()

add_library(wordle_sqlite INTERFACE)
find_package(SQLite3 CONFIG QUIET)
if(NOT TARGET SQLite3::SQLite3 AND NOT TARGET SQLite::SQLite3)
    find_package(SQLite3 QUIET)
endif()
if(TARGET SQLite3::SQLite3)
    target_link_libraries(wordle_sqlite INTERFACE SQLite3::SQLite3)
elseif(TARGET SQLite::SQLite3)
    target_link_libraries(wordle_sqlite INTERFACE SQLite::SQLite3)
else()
    if(PkgConfig_FOUND)
        pkg_check_modules(SQLITE QUIET IMPORTED_TARGET sqlite3)
    endif()
    if(TARGET PkgConfig::SQLITE)
        target_link_libraries(wordle_sqlite INTERFACE PkgConfig::SQLITE)
    else()
        find_package(unofficial-sqlite3 CONFIG REQUIRED)
        target_link_libraries(wordle_sqlite INTERFACE unofficial::sqlite3::sqlite3)
    endif()
endif()

add_library(wordle_icu INTERFACE)
find_package(ICU CONFIG QUIET)
if(NOT TARGET ICU::uc OR NOT TARGET ICU::i18n)
    find_package(ICU QUIET COMPONENTS uc i18n data)
endif()
if(TARGET ICU::uc AND TARGET ICU::i18n)
    target_link_libraries(wordle_icu INTERFACE ICU::uc ICU::i18n)
    if(TARGET ICU::data)
        target_link_libraries(wordle_icu INTERFACE ICU::data)
    endif()
else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(ICU_PC REQUIRED IMPORTED_TARGET icu-uc icu-i18n)
    target_link_libraries(wordle_icu INTERFACE PkgConfig::ICU_PC)
endif()
