option(WORDLE_ENABLE_LUA "Build the Lua 5.4+ rule backend" ON)

if(WORDLE_ENABLE_LUA)
    find_package(lua CONFIG QUIET)
    find_package(Lua 5.4 CONFIG QUIET)
    target_sources(libwordle PRIVATE src/plugins/lua.cpp)
    if(TARGET lua::lua)
        target_link_libraries(libwordle PUBLIC lua::lua)
    elseif(TARGET Lua::Lua)
        target_link_libraries(libwordle PUBLIC Lua::Lua)
    else()
        find_package(Lua 5.4 REQUIRED)
        target_include_directories(libwordle PRIVATE ${LUA_INCLUDE_DIR})
        target_link_libraries(libwordle PUBLIC ${LUA_LIBRARIES})
    endif()
    target_compile_definitions(libwordle PRIVATE WORDLE_HAS_LUA=1)
endif()
